; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

include listing.inc

INCLUDELIB OLDNAMES

PI_MUL_2 DD	040c90fdbr			; 6.28319
PUBLIC	?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z	; CFileStreamReader::construct
PUBLIC	?destroy@CFileStreamReader@@UEAAXXZ		; CFileStreamReader::destroy
pdata	SEGMENT
$pdata$?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z DD imagerel $LN24
	DD	imagerel $LN24+274
	DD	imagerel $unwind$?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z
$pdata$?destroy@CFileStreamReader@@UEAAXXZ DD imagerel $LN10
	DD	imagerel $LN10+57
	DD	imagerel $unwind$?destroy@CFileStreamReader@@UEAAXXZ
xdata	SEGMENT
$unwind$?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z DD 081401H
	DD	0c6414H
	DD	0b5414H
	DD	0a3414H
	DD	070107214H
$unwind$?destroy@CFileStreamReader@@UEAAXXZ DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader_inline.h
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
_TEXT	SEGMENT
this$ = 48
?destroy@CFileStreamReader@@UEAAXXZ PROC		; CFileStreamReader::destroy

; 35   : {

$LN10:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H

; 36   : 	HANDLE					file_mapping_handle = this->file_mapping_handle();

	mov	rbx, QWORD PTR [rcx+8]
	mov	rdi, rcx
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader_inline.h

; 30   : 	UnmapViewOfFile	(m_current_map_view_of_file);

	mov	rcx, QWORD PTR [rcx+40]
	call	QWORD PTR __imp_UnmapViewOfFile
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp

; 38   : 	CloseHandle				(file_mapping_handle);

	mov	rcx, rbx
	call	QWORD PTR __imp_CloseHandle

; 39   : 	CloseHandle				(m_file_handle);

	mov	rcx, QWORD PTR [rdi+64]

; 40   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi

; 39   : 	CloseHandle				(m_file_handle);

	rex_jmp	QWORD PTR __imp_CloseHandle
?destroy@CFileStreamReader@@UEAAXXZ ENDP		; CFileStreamReader::destroy
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\_std_extensions.h
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp
_TEXT	SEGMENT
this$ = 80
file_name$ = 88
window_size$ = 96
?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z PROC	; CFileStreamReader::construct

; 5    : {

$LN24:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 64					; 00000040H

; 6    : 	m_file_handle			=
; 7    : 		CreateFile(
; 8    : 			file_name,
; 9    : 			GENERIC_READ,
; 10   : 			FILE_SHARE_READ,
; 11   : 			0,
; 12   : 			OPEN_EXISTING,
; 13   : 			0,
; 14   : 			0
; 15   : 		);

	xor	ebp, ebp
	mov	rax, rdx
	mov	rbx, r8
	mov	rdi, rcx
	mov	QWORD PTR [rsp+48], rbp
	lea	r8d, QWORD PTR [rbp+1]
	xor	r9d, r9d
	mov	edx, -2147483648			; 80000000H
	mov	rcx, rax
	mov	DWORD PTR [rsp+40], ebp
	mov	DWORD PTR [rsp+32], 3
	call	QWORD PTR __imp_CreateFileA

; 16   : 
; 17   : 	VERIFY					(m_file_handle != INVALID_HANDLE_VALUE);
; 18   : 	u32						file_size = (u32)GetFileSize(m_file_handle,NULL);

	mov	rcx, rax
	xor	edx, edx
	mov	QWORD PTR [rdi+64], rax
	call	QWORD PTR __imp_GetFileSize

; 28   : 		);

	mov	rcx, QWORD PTR [rdi+64]
	lea	r8d, QWORD PTR [rbp+2]
	xor	r9d, r9d
	xor	edx, edx
	mov	QWORD PTR [rsp+40], rbp
	mov	esi, eax
	mov	DWORD PTR [rsp+32], ebp
	call	QWORD PTR __imp_CreateFileMappingA
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp

; 12   : 	m_file_mapping_handle		= file_mapping_handle;

	mov	QWORD PTR [rdi+8], rax

; 13   : 	m_start_offset				= start_offset;

	mov	DWORD PTR [rdi+16], ebp

; 14   : 	m_file_size					= file_size;

	mov	DWORD PTR [rdi+20], esi

; 15   : 	m_archive_size				= archive_size;

	mov	DWORD PTR [rdi+24], esi

; 16   : 	m_window_size				= _max(window_size,FS.dwAllocGranularity);

	mov	rcx, QWORD PTR ?xr_FS@@3PEAVCLocatorAPI@@EA ; xr_FS
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp

; 28   : 		);

	mov	r10, rax
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp

; 16   : 	m_window_size				= _max(window_size,FS.dwAllocGranularity);

	mov	r8d, DWORD PTR [rcx+116]
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\_std_extensions.h

; 94   : template <class T>	IC T		_max	(T a, T b)	{ return a>b?a:b;	}

	cmp	DWORD PTR [rbx], r8d
	cmova	r8d, DWORD PTR [rbx]
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp

; 34   : 	start_offset				= (start_offset/granularity)*granularity;

	xor	edx, edx
	xor	eax, eax

; 16   : 	m_window_size				= _max(window_size,FS.dwAllocGranularity);

	mov	DWORD PTR [rdi+28], r8d

; 17   : 
; 18   : 	map							(0);
; 19   : }
; 20   : 
; 21   : void CStreamReader::destroy					()
; 22   : {
; 23   : 	unmap						();
; 24   : }
; 25   : 
; 26   : void CStreamReader::map						(const u32 &new_offset)
; 27   : {
; 28   : 	VERIFY						(new_offset <= m_file_size);
; 29   : 	m_current_offset_from_start	= new_offset;

	mov	DWORD PTR [rdi+32], ebp

; 30   : 
; 31   : 	u32							granularity = FS.dwAllocGranularity;

	mov	rcx, QWORD PTR ?xr_FS@@3PEAVCLocatorAPI@@EA ; xr_FS
	mov	r9d, DWORD PTR [rcx+116]

; 34   : 	start_offset				= (start_offset/granularity)*granularity;

	div	r9d

; 35   : 
; 36   : 	VERIFY						(pure_start_offset >= start_offset);
; 37   : 	u32							pure_end_offset = m_window_size + pure_start_offset;
; 38   : 	u32							end_offset = pure_end_offset/granularity;

	xor	edx, edx
	mov	ebx, eax
	mov	eax, r8d
	div	r9d
	imul	ebx, r9d

; 39   : 	if (pure_end_offset%granularity)

	test	edx, edx
	je	SHORT $LN14@construct

; 40   : 		++end_offset;

	inc	eax
$LN14@construct:

; 41   : 
; 42   : 	end_offset					*= granularity;

	imul	eax, r9d

; 54   : 		);

	mov	rcx, r10
	mov	r9d, ebx
	cmp	eax, esi
	cmova	eax, esi
	xor	r8d, r8d
	sub	eax, ebx
	lea	edx, QWORD PTR [r8+4]
	mov	DWORD PTR [rdi+36], eax
	mov	QWORD PTR [rsp+32], rax
	call	QWORD PTR __imp_MapViewOfFile
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp

; 32   : }

	mov	rbp, QWORD PTR [rsp+88]
	mov	rsi, QWORD PTR [rsp+96]
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp

; 57   : 	u32							difference = pure_start_offset - start_offset;

	neg	ebx

; 58   : 	m_current_window_size		-= difference;

	sub	DWORD PTR [rdi+36], ebx

; 59   : 	m_current_pointer			+= difference;

	mov	ecx, ebx
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp

; 32   : }

	mov	rbx, QWORD PTR [rsp+80]
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\stream_reader.cpp

; 54   : 		);

	mov	QWORD PTR [rdi+40], rax

; 59   : 	m_current_pointer			+= difference;

	add	rax, rcx
	mov	QWORD PTR [rdi+56], rax

; 60   : 	m_start_pointer				= m_current_pointer;

	mov	QWORD PTR [rdi+48], rax
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\file_stream_reader.cpp

; 32   : }

	add	rsp, 64					; 00000040H
	pop	rdi
	ret	0
?construct@CFileStreamReader@@UEAAXPEBDAEBI@Z ENDP	; CFileStreamReader::construct
_TEXT	ENDS
END
