; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?xrMemCopy_MMX@@YAXPEAXPEBXI@Z			; xrMemCopy_MMX
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcore\xrmemory_pso_copy.cpp
_TEXT	SEGMENT
dest$ = 8
src$ = 16
n$ = 24
?xrMemCopy_MMX@@YAXPEAXPEBXI@Z PROC			; xrMemCopy_MMX

; 13   : 	memcpy		(dest,src,n);

	mov	r8d, r8d

; 14   : }

	jmp	memcpy
?xrMemCopy_MMX@@YAXPEAXPEBXI@Z ENDP			; xrMemCopy_MMX
_TEXT	ENDS
PUBLIC	?xrMemCopy_x86@@YAXPEAXPEBXI@Z			; xrMemCopy_x86
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
dest$ = 8
src$ = 16
n$ = 24
?xrMemCopy_x86@@YAXPEAXPEBXI@Z PROC			; xrMemCopy_x86

; 7    : 	memcpy		(dest,src,n);

	mov	r8d, r8d

; 8    : }

	jmp	memcpy
?xrMemCopy_x86@@YAXPEAXPEBXI@Z ENDP			; xrMemCopy_x86
END
