; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??0Matrix4x4@IceMaths@@QEAA@MMMMMMMMMMMMMMMM@Z	; IceMaths::Matrix4x4::Matrix4x4
PUBLIC	??1Matrix4x4@IceMaths@@QEAA@XZ			; IceMaths::Matrix4x4::~Matrix4x4
PUBLIC	?Normalize@icePoint@IceMaths@@QEAAAEAV12@XZ	; IceMaths::icePoint::Normalize
PUBLIC	?Zero@Matrix3x3@IceMaths@@QEAAXXZ		; IceMaths::Matrix3x3::Zero
PUBLIC	?Identity@Matrix3x3@IceMaths@@QEAAXXZ		; IceMaths::Matrix3x3::Identity
END
