; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

include listing.inc

INCLUDELIB OLDNAMES

;	COMDAT ?Indices@?1??GetLineIndices@OBB@Meshmerizer@@QEBAPEBIXZ@4PAIA
_DATA	SEGMENT
?Indices@?1??GetLineIndices@OBB@Meshmerizer@@QEBAPEBIXZ@4PAIA DD 00H ; `Meshmerizer::OBB::GetLineIndices'::`2'::Indices
	DD	01H
	DD	01H
	DD	02H
	DD	02H
	DD	03H
	DD	03H
	DD	00H
	DD	01H
	DD	05H
	DD	05H
	DD	06H
	DD	06H
	DD	02H
	DD	02H
	DD	01H
	DD	07H
	DD	06H
	DD	06H
	DD	05H
	DD	05H
	DD	04H
	DD	04H
	DD	07H
	DD	03H
	DD	07H
	DD	07H
	DD	04H
	DD	04H
	DD	00H
	DD	00H
	DD	03H
	DD	04H
	DD	05H
	DD	05H
	DD	01H
	DD	01H
	DD	00H
	DD	00H
	DD	04H
	DD	03H
	DD	02H
	DD	02H
	DD	06H
	DD	06H
	DD	07H
	DD	07H
	DD	03H
PUBLIC	??1Matrix3x3@IceMaths@@QEAA@XZ			; IceMaths::Matrix3x3::~Matrix3x3
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcdb\opc_matrix3x3.h
;	COMDAT ??1Matrix3x3@IceMaths@@QEAA@XZ
_TEXT	SEGMENT
this$dead$ = 8
??1Matrix3x3@IceMaths@@QEAA@XZ PROC			; IceMaths::Matrix3x3::~Matrix3x3, COMDAT

; 36   : 		inline_					~Matrix3x3()								{}

	ret	0
??1Matrix3x3@IceMaths@@QEAA@XZ ENDP			; IceMaths::Matrix3x3::~Matrix3x3
_TEXT	ENDS
END
