; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?ValidateSettings@AABBTreeCollider@Opcode@@UEAAPEBDXZ ; Opcode::AABBTreeCollider::ValidateSettings
PUBLIC	??_R4AABBTreeCollider@Opcode@@6B@		; Opcode::AABBTreeCollider::`RTTI Complete Object Locator'
PUBLIC	??_R3AABBTreeCollider@Opcode@@8			; Opcode::AABBTreeCollider::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2AABBTreeCollider@Opcode@@8			; Opcode::AABBTreeCollider::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@AABBTreeCollider@Opcode@@8	; Opcode::AABBTreeCollider::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVAABBTreeCollider@Opcode@@@8		; Opcode::AABBTreeCollider `RTTI Type Descriptor'
PUBLIC	??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z	; Opcode::AABBTreeCollider::`scalar deleting destructor'
PUBLIC	?GetSize@AABBQuantizedNode@Opcode@@QEBAGXZ	; Opcode::AABBQuantizedNode::GetSize
PUBLIC	?PrimTestIndexTri@AABBTreeCollider@Opcode@@IEAAXI@Z ; Opcode::AABBTreeCollider::PrimTestIndexTri
PUBLIC	?TriBoxOverlap@AABBTreeCollider@Opcode@@IEAAHAEBVicePoint@IceMaths@@0@Z ; Opcode::AABBTreeCollider::TriBoxOverlap
PUBLIC	?TriTriOverlap@AABBTreeCollider@Opcode@@IEAAHAEBVicePoint@IceMaths@@00000@Z ; Opcode::AABBTreeCollider::TriTriOverlap
PUBLIC	?PrimTestTriIndex@AABBTreeCollider@Opcode@@IEAAXI@Z ; Opcode::AABBTreeCollider::PrimTestTriIndex
PUBLIC	?BoxBoxOverlap@AABBTreeCollider@Opcode@@IEAAHAEBVicePoint@IceMaths@@000@Z ; Opcode::AABBTreeCollider::BoxBoxOverlap
PUBLIC	??_C@_0DI@JNJMPNPG@Object0?5pointers?5must?5be?5defined@ ; `string'
PUBLIC	??_C@_0DI@CEMNMNLH@Object1?5pointers?5must?5be?5defined@ ; `string'
PUBLIC	??_7AABBTreeCollider@Opcode@@6B@		; Opcode::AABBTreeCollider::`vftable'
EXTRN	??_EAABBTreeCollider@Opcode@@UEAAPEAXI@Z:PROC	; Opcode::AABBTreeCollider::`vector deleting destructor'
;	COMDAT ??_7AABBTreeCollider@Opcode@@6B@
CONST	SEGMENT
??_7AABBTreeCollider@Opcode@@6B@ DQ FLAT:??_R4AABBTreeCollider@Opcode@@6B@ ; Opcode::AABBTreeCollider::`vftable'
	DQ	FLAT:??_EAABBTreeCollider@Opcode@@UEAAPEAXI@Z
	DQ	FLAT:?ValidateSettings@AABBTreeCollider@Opcode@@UEAAPEBDXZ
	DQ	FLAT:?InitQueryEx@Collider@Opcode@@MEAAXXZ
CONST	ENDS
;	COMDAT ??_R4AABBTreeCollider@Opcode@@6B@
rdata$r	SEGMENT
??_R4AABBTreeCollider@Opcode@@6B@ DD 01H		; Opcode::AABBTreeCollider::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVAABBTreeCollider@Opcode@@@8
	DD	imagerel ??_R3AABBTreeCollider@Opcode@@8
	DD	imagerel ??_R4AABBTreeCollider@Opcode@@6B@
rdata$r	ENDS
;	COMDAT ??_R3AABBTreeCollider@Opcode@@8
rdata$r	SEGMENT
??_R3AABBTreeCollider@Opcode@@8 DD 00H			; Opcode::AABBTreeCollider::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2AABBTreeCollider@Opcode@@8
rdata$r	ENDS
;	COMDAT ??_R2AABBTreeCollider@Opcode@@8
rdata$r	SEGMENT
??_R2AABBTreeCollider@Opcode@@8 DD imagerel ??_R1A@?0A@EA@AABBTreeCollider@Opcode@@8 ; Opcode::AABBTreeCollider::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@Collider@Opcode@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@AABBTreeCollider@Opcode@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@AABBTreeCollider@Opcode@@8 DD imagerel ??_R0?AVAABBTreeCollider@Opcode@@@8 ; Opcode::AABBTreeCollider::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3AABBTreeCollider@Opcode@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVAABBTreeCollider@Opcode@@@8
_DATA	SEGMENT
??_R0?AVAABBTreeCollider@Opcode@@@8 DQ FLAT:??_7type_info@@6B@ ; Opcode::AABBTreeCollider `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVAABBTreeCollider@Opcode@@', 00H
_DATA	ENDS
;	COMDAT ??_C@_0DI@CEMNMNLH@Object1?5pointers?5must?5be?5defined@
CONST	SEGMENT
??_C@_0DI@CEMNMNLH@Object1?5pointers?5must?5be?5defined@ DB 'Object1 poin'
	DB	'ters must be defined! Call: SetPointers1().', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DI@JNJMPNPG@Object0?5pointers?5must?5be?5defined@
CONST	SEGMENT
??_C@_0DI@JNJMPNPG@Object0?5pointers?5must?5be?5defined@ DB 'Object0 poin'
	DB	'ters must be defined! Call: SetPointers0().', 00H ; `string'
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcdb\opc_treecollider.cpp
_TEXT	SEGMENT
this$ = 8
?ValidateSettings@AABBTreeCollider@Opcode@@UEAAPEBDXZ PROC ; Opcode::AABBTreeCollider::ValidateSettings

; 83   : #ifdef OPC_USE_CALLBACKS
; 84   : 	if(!mObjCallback0)											return "Callback for object 0 must be defined! Call: SetCallback0().";
; 85   : 	if(!mObjCallback1)											return "Callback for object 1 must be defined! Call: SetCallback1().";
; 86   : #else
; 87   : 	if(!mFaces0 || !mVerts0)									return "Object0 pointers must be defined! Call: SetPointers0().";

	cmp	QWORD PTR [rcx+40], 0
	je	SHORT $LN4@ValidateSe@4
	cmp	QWORD PTR [rcx+56], 0
	je	SHORT $LN4@ValidateSe@4

; 88   : 	if(!mFaces1 || !mVerts1)									return "Object1 pointers must be defined! Call: SetPointers1().";

	cmp	QWORD PTR [rcx+48], 0
	je	SHORT $LN2@ValidateSe@4
	cmp	QWORD PTR [rcx+64], 0
	je	SHORT $LN2@ValidateSe@4

; 89   : #endif
; 90   : 	if(TemporalCoherenceEnabled() && !FirstContactEnabled())	return "Temporal coherence only works with ""First contact"" mode!";

	mov	eax, DWORD PTR [rcx+8]
	test	al, 2
	je	SHORT $LN1@ValidateSe@4
	test	al, 1
	jne	SHORT $LN1@ValidateSe@4
	lea	rax, OFFSET FLAT:??_C@_0DH@CENBPGJM@Temporal?5coherence?5only?5works?5wi@

; 92   : }

	ret	0
$LN1@ValidateSe@4:

; 91   : 	return null;

	xor	eax, eax

; 92   : }

	ret	0
$LN2@ValidateSe@4:

; 88   : 	if(!mFaces1 || !mVerts1)									return "Object1 pointers must be defined! Call: SetPointers1().";

	lea	rax, OFFSET FLAT:??_C@_0DI@CEMNMNLH@Object1?5pointers?5must?5be?5defined@

; 92   : }

	ret	0
$LN4@ValidateSe@4:

; 83   : #ifdef OPC_USE_CALLBACKS
; 84   : 	if(!mObjCallback0)											return "Callback for object 0 must be defined! Call: SetCallback0().";
; 85   : 	if(!mObjCallback1)											return "Callback for object 1 must be defined! Call: SetCallback1().";
; 86   : #else
; 87   : 	if(!mFaces0 || !mVerts0)									return "Object0 pointers must be defined! Call: SetPointers0().";

	lea	rax, OFFSET FLAT:??_C@_0DI@JNJMPNPG@Object0?5pointers?5must?5be?5defined@

; 92   : }

	ret	0
?ValidateSettings@AABBTreeCollider@Opcode@@UEAAPEBDXZ ENDP ; Opcode::AABBTreeCollider::ValidateSettings
PUBLIC	??1AABBTreeCollider@Opcode@@UEAA@XZ		; Opcode::AABBTreeCollider::~AABBTreeCollider
pdata	SEGMENT
$pdata$??1AABBTreeCollider@Opcode@@UEAA@XZ DD imagerel $LN40
	DD	imagerel $LN40+114
	DD	imagerel $unwind$??1AABBTreeCollider@Opcode@@UEAA@XZ
pdata	ENDS
xdata	SEGMENT
$unwind$??1AABBTreeCollider@Opcode@@UEAA@XZ DD 020601H
	DD	030023206H
; Function compile flags: /Ogtpy
xdata	ENDS
_TEXT	SEGMENT
this$ = 48
??1AABBTreeCollider@Opcode@@UEAA@XZ PROC		; Opcode::AABBTreeCollider::~AABBTreeCollider

; 72   : {

$LN40:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	lea	rax, OFFSET FLAT:??_7AABBTreeCollider@Opcode@@6B@
	mov	QWORD PTR [rcx], rax

; 73   : }

	mov	eax, DWORD PTR [rcx+16]
	mov	ecx, DWORD PTR ?mUsedRam@Container@IceCore@@0IA ; IceCore::Container::mUsedRam
	mov	rdx, QWORD PTR [rbx+24]
	imul	eax, -4					; fffffffcH
	add	ecx, eax
	mov	DWORD PTR ?mUsedRam@Container@IceCore@@0IA, ecx ; IceCore::Container::mUsedRam
	test	rdx, rdx
	je	SHORT $LN31@AABBTreeCo
	mov	rcx, QWORD PTR __imp_?Memory@@3VxrMemory@@A
	call	QWORD PTR __imp_?mem_free@xrMemory@@QEAAXPEAX@Z
	mov	ecx, DWORD PTR ?mUsedRam@Container@IceCore@@0IA ; IceCore::Container::mUsedRam
	mov	QWORD PTR [rbx+24], 0
$LN31@AABBTreeCo:
	dec	DWORD PTR ?mNbContainers@Container@IceCore@@0IA ; IceCore::Container::mNbContainers
	lea	rax, OFFSET FLAT:??_7Collider@Opcode@@6B@
	add	ecx, -24				; ffffffe8H
	mov	QWORD PTR [rbx+16], 0
	mov	DWORD PTR ?mUsedRam@Container@IceCore@@0IA, ecx ; IceCore::Container::mUsedRam
	mov	QWORD PTR [rbx], rax
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??1AABBTreeCollider@Opcode@@UEAA@XZ ENDP		; Opcode::AABBTreeCollider::~AABBTreeCollider
_TEXT	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z DD imagerel $LN11
	DD	imagerel $LN11+60
	DD	imagerel $unwind$??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z PROC		; Opcode::AABBTreeCollider::`scalar deleting destructor', COMDAT
$LN11:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	ebx, edx
	mov	rdi, rcx
	call	??1AABBTreeCollider@Opcode@@UEAA@XZ	; Opcode::AABBTreeCollider::~AABBTreeCollider
	test	bl, 1
	je	SHORT $LN10@scalar@12
	test	rdi, rdi
	je	SHORT $LN10@scalar@12
	mov	rcx, QWORD PTR __imp_?Memory@@3VxrMemory@@A
	mov	rdx, rdi
	call	QWORD PTR __imp_?mem_free@xrMemory@@QEAAXPEAX@Z
$LN10@scalar@12:
	mov	rax, rdi
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??_GAABBTreeCollider@Opcode@@UEAAPEAXI@Z ENDP		; Opcode::AABBTreeCollider::`scalar deleting destructor'
END
