; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?ValidateSettings@VolumeCollider@Opcode@@UEAAPEBDXZ ; Opcode::VolumeCollider::ValidateSettings
PUBLIC	??_R4VolumeCollider@Opcode@@6B@			; Opcode::VolumeCollider::`RTTI Complete Object Locator'
PUBLIC	??_7VolumeCollider@Opcode@@6B@			; Opcode::VolumeCollider::`vftable'
;	COMDAT ??_7VolumeCollider@Opcode@@6B@
CONST	SEGMENT
??_7VolumeCollider@Opcode@@6B@ DQ FLAT:??_R4VolumeCollider@Opcode@@6B@ ; Opcode::VolumeCollider::`vftable'
	DQ	FLAT:_purecall
	DQ	FLAT:?ValidateSettings@VolumeCollider@Opcode@@UEAAPEBDXZ
	DQ	FLAT:?InitQueryEx@VolumeCollider@Opcode@@MEAAXXZ
CONST	ENDS
;	COMDAT ??_R4VolumeCollider@Opcode@@6B@
rdata$r	SEGMENT
??_R4VolumeCollider@Opcode@@6B@ DD 01H			; Opcode::VolumeCollider::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVVolumeCollider@Opcode@@@8
	DD	imagerel ??_R3VolumeCollider@Opcode@@8
	DD	imagerel ??_R4VolumeCollider@Opcode@@6B@
; Function compile flags: /Ogtpy
; File c:\users\nummer\documents\github\olr-3.0\src\xray\xrcdb\opc_volumecollider.cpp
rdata$r	ENDS
_TEXT	SEGMENT
this$ = 8
?ValidateSettings@VolumeCollider@Opcode@@UEAAPEBDXZ PROC ; Opcode::VolumeCollider::ValidateSettings

; 73   : #ifdef OPC_USE_CALLBACKS
; 74   : 	if(!mObjCallback)		return "Object callback must be defined! Call: SetCallback().";
; 75   : #else
; 76   : 	if(!mFaces || !mVerts)	return "Object pointers must be defined! Call: SetPointers().";

	cmp	QWORD PTR [rcx+24], 0
	je	SHORT $LN1@ValidateSe
	cmp	QWORD PTR [rcx+32], 0
	je	SHORT $LN1@ValidateSe

; 77   : #endif
; 78   : 	return null;

	xor	eax, eax

; 79   : }

	ret	0
$LN1@ValidateSe:

; 73   : #ifdef OPC_USE_CALLBACKS
; 74   : 	if(!mObjCallback)		return "Object callback must be defined! Call: SetCallback().";
; 75   : #else
; 76   : 	if(!mFaces || !mVerts)	return "Object pointers must be defined! Call: SetPointers().";

	lea	rax, OFFSET FLAT:??_C@_0DG@GPJAOPIP@Object?5pointers?5must?5be?5defined?$CB@

; 79   : }

	ret	0
?ValidateSettings@VolumeCollider@Opcode@@UEAAPEBDXZ ENDP ; Opcode::VolumeCollider::ValidateSettings
PUBLIC	??1VolumeCollider@Opcode@@UEAA@XZ		; Opcode::VolumeCollider::~VolumeCollider
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
this$ = 8
??1VolumeCollider@Opcode@@UEAA@XZ PROC			; Opcode::VolumeCollider::~VolumeCollider

; 62   : 	mTouchedPrimitives = null;
; 63   : }

	lea	rax, OFFSET FLAT:??_7Collider@Opcode@@6B@
	mov	QWORD PTR [rcx+16], 0
	mov	QWORD PTR [rcx], rax
	ret	0
??1VolumeCollider@Opcode@@UEAA@XZ ENDP			; Opcode::VolumeCollider::~VolumeCollider
END
